on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-example:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'

      - run: sudo apt-get update && sudo apt-get install -y docker-compose

      - run: git clone https://github.com/Golem-Base/golembase-op-geth.git

      - run: docker-compose up -d
        working-directory: ./golembase-op-geth

      - run: |
          go install github.com/Golem-Base/golembase-demo-cli@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - run: |
          ADDRESS=$(golembase-demo-cli account create | grep -oE '0x[a-fA-F0-9]{40}')
          echo "ADDRESS=$ADDRESS" >> $GITHUB_ENV

      - run: |
          curl 'https://faucet.golembase.demo.golem-base.io/api/faucet' \
            -H 'Content-Type: application/json' \
            --data-raw "{\"address\":\"$ADDRESS\"}"
          golembase-demo-cli account balance

      - run: nix build .#golem-base-sdk-example --no-write-lock-file
        working-directory: ./example

      - run: ./result/bin/main
        working-directory: ./example

      - run: docker-compose down
        working-directory: ./golembase-op-geth
