on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-python-example:
    runs-on: ubuntu-latest

    services:
      gb-op-geth:
        image: "quay.io/golemnetwork/gb-op-geth:latest"
        ports:
          - 8545:8545
        options: |
          --entrypoint "go run ../cmd/geth --dev --http --http.api 'eth,web3,net,debug,golembase' --verbosity 3 --http.addr '0.0.0.0' --http.port 8545 --http.corsdomain '*' --http.vhosts '*' --ws --ws.addr '0.0.0.0' --ws.port 8545"

    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: Golem-Base/golembase-op-geth
          path: gb-op-geth

      - uses: cachix/install-nix-action@v31

      - uses: actions/setup-go@v5
        with:
          go-version: "1.24.2"

      - run: |
          go run ./cmd/golembase account create
          go run ./cmd/golembase account fund
        working-directory: ./gb-op-geth

      - run: nix build .#golem-base-sdk-example --no-write-lock-file
        working-directory: ./example

      - run: ./result/bin/main --instance local
        working-directory: ./example
